version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fp-ts
    versions:
    - 2.9.3
    - 2.9.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: typescript
    versions:
    - 3.9.7
  - dependency-name: handlebars
    versions:
    - 4.7.6
